spring:
  datasource:
    url: jdbc:mysql://localhost:3306/admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.MySQLDialect

# App Properties
jwt:
  keys:
    jwtSecret: bezKoderSecretKeyadadasdaascascascascascascascdascascascacascascasc
    jwtExpirationMs: 86400000
    
abc:
  xyz: Ridisha
