server:
  port: 8008
spring:
  application:
    name: admin-service
  datasource:
    url: jdbc:mysql://localhost:3306/my_school
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

